import { DashboardTool } from "./schemas";

/**
 * Rewrites the API endpoints within a UI Configuration to point to a cached Snapshot.
 * This ensures that when the client renders the component, it fetches the exact data
 * the AI "saw" during generation, rather than re-querying the database.
 * 
 * @param config The original Dashboard Configuration generated by AI
 * @param snapshotId The ID of the snapshot stored in SnapshotService
 * @returns A new configuration object with /api/snapshots/[id] URLs
 */
export function injectSnapshotIntoConfig(config: DashboardTool, snapshotId: string): DashboardTool {
  const snapshotUrl = `/api/snapshots/${snapshotId}`;
  const newConfig = JSON.parse(JSON.stringify(config)); // Deep clone to avoid mutation

  if (newConfig.layout === "dashboard") {
    if (newConfig.slotMain) {
      newConfig.slotMain.apiEndpoint = `${snapshotUrl}?key=slotMain`;
    }
    if (newConfig.slotRightTop) {
      newConfig.slotRightTop.apiEndpoint = `${snapshotUrl}?key=slotRightTop`;
    }
    if (newConfig.slotRightBottom) {
      newConfig.slotRightBottom.apiEndpoint = `${snapshotUrl}?key=slotRightBottom`;
    }
    // Note: We deliberately do NOT overwrite headerStats here in this version.
    // Ideally, headerStats might need their own snapshots or a composite snapshot.
    // For now, only the main visualization is snapshot-backed.
  } else if (newConfig.layout === "single") {
    newConfig.config.apiEndpoint = snapshotUrl;
  } else if (newConfig.layout === "split") {
    newConfig.leftChart.apiEndpoint = snapshotUrl;
    newConfig.rightChart.apiEndpoint = snapshotUrl;
  }
  
  return newConfig;
}
