"use client";

import React from "react";
import { SmartChart } from "@/components/genui/SmartChart";
import { KPIGrid } from "@/components/genui/KPIGrid";
import { SmartTable } from "@/components/genui/SmartTable";
import { SplitLayout } from "@/components/layout/SplitLayout";
import { SmartStatCard } from "@/components/genui/SmartStatCard";
import type { DashboardTool, ChartConfig } from "@/lib/genui/schemas";

interface StatItem {
  title: string;
  apiEndpoint: string;
  dataKey: string;
  filter?: string;
}

// --- Analytics Isolated Default Data ---
const defaultStats: StatItem[] = [
  { title: "Total employees", apiEndpoint: "/api/github/usage", dataKey: "summary.active_users" },
  { title: "Loyalty account", apiEndpoint: "/api/github/usage", dataKey: "summary.active_users" },
  { title: "Average income", apiEndpoint: "/api/github/usage", dataKey: "summary.active_users", filter: "Month" },
  { title: "Campaign sent", apiEndpoint: "/api/github/usage", dataKey: "summary.active_users", filter: "Month" },
];

interface AnalyticsRendererProps {
  config: DashboardTool | null;
}

export function AnalyticsRenderer({ config }: AnalyticsRendererProps) {
  const renderToolComponent = (cfg: ChartConfig) => {
    if (cfg.component === 'KPIGrid') {
      return <KPIGrid apiEndpoint={cfg.apiEndpoint} definitions={cfg.kpiDefinitions} />;
    }
    if (cfg.component === 'SmartTable') {
      return <SmartTable apiEndpoint={cfg.apiEndpoint} title={cfg.title} columns={cfg.tableColumns || []} />;
    }
    return <SmartChart apiEndpoint={cfg.apiEndpoint} title={cfg.title} filter={cfg.filter} xAxisKey={cfg.xAxisKey} series={cfg.chartSeries} />;
  };

  const renderCenterContent = () => {
    if (!config) {
      return (
        <div className="h-full bg-[var(--color-unit)] p-6 rounded-xl shadow-sm border border-[color:var(--color-stroke)] flex flex-col items-center justify-center text-center">
          <div className="w-16 h-16 bg-[var(--color-soft-lavender)] rounded-full flex items-center justify-center mb-4">
            <span className="text-2xl">📈</span>
          </div>
          <h3 className="text-lg font-semibold text-[color:var(--color-primary)]">Analytics Ready</h3>
          <p className="text-[color:var(--color-secondary)] mt-2 max-w-sm">
            Open the Copilot chat on the right and ask for complex analysis.
          </p>
        </div>
      );
    }

    if (config.layout === 'dashboard') {
      return (
        <div className="bg-[var(--color-unit)] p-6 rounded-xl shadow-sm border border-[color:var(--color-stroke)] animate-in fade-in zoom-in duration-500 h-full">
          <div className="mb-4 flex items-center justify-between">
            <h3 className="text-lg font-semibold text-[color:var(--color-primary)]">{config.slotMain.title}</h3>
            <span className="text-xs font-medium text-[color:var(--color-highlight)] bg-[var(--color-soft-lavender)] px-2 py-1 rounded-full">Generated by Copilot</span>
          </div>
          {renderToolComponent(config.slotMain)}
        </div>
      );
    }

    if (config.layout === 'single') {
      return (
        <div className="bg-[var(--color-unit)] p-6 rounded-xl shadow-sm border border-[color:var(--color-stroke)] animate-in fade-in zoom-in duration-500 h-full">
          <div className="mb-4 flex items-center justify-between">
            <h3 className="text-lg font-semibold text-[color:var(--color-primary)]">{config.config.title}</h3>
            <span className="text-xs font-medium text-[color:var(--color-highlight)] bg-[var(--color-soft-lavender)] px-2 py-1 rounded-full">Generated by Copilot</span>
          </div>
          {renderToolComponent(config.config)}
        </div>
      );
    }

    if (config.layout === 'split') {
      return (
        <div className="bg-[var(--color-unit)] p-6 rounded-xl shadow-sm border border-[color:var(--color-stroke)] animate-in fade-in zoom-in duration-500 h-full">
          <div className="mb-4 flex items-center justify-between">
            <h3 className="text-lg font-semibold text-[color:var(--color-primary)]">Comparison View</h3>
            <span className="text-xs font-medium text-[color:var(--color-highlight)] bg-[var(--color-soft-lavender)] px-2 py-1 rounded-full">Generated by Copilot</span>
          </div>
          <SplitLayout 
            left={renderToolComponent(config.leftChart)}
            right={renderToolComponent(config.rightChart)}
          />
        </div>
      );
    }
    return null;
  };

  const currentStats = (config?.layout === 'dashboard' && config.headerStats) ? config.headerStats : defaultStats;

  return (
    <div className="flex flex-col h-full">
      <section className="mb-6">
        <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">
          {currentStats.map((item, i) => (
            <SmartStatCard key={i} {...(item as StatItem)} />
          ))}
        </div>
      </section>

      <section className="flex-1 min-h-[400px]">
        {renderCenterContent()}
      </section>
    </div>
  );
}