"use client";

import React from "react";
import { SmartChart } from "@/components/genui/SmartChart";
import { KPIGrid } from "@/components/genui/KPIGrid";
import { SmartTable } from "@/components/genui/SmartTable";
import { SplitLayout } from "@/components/layout/SplitLayout";
import { Calendar } from "@/components/ui/Calendar";
import { SmartStatCard } from "@/components/genui/SmartStatCard";
import type { DashboardTool, ChartConfig } from "@/lib/genui/schemas";

interface StatItem {
  title: string;
  apiEndpoint: string;
  dataKey: string;
  accent: string;
  trendKey?: string;
  filter?: string;
}

// --- Analytics Isolated Default Data ---
const defaultStats: StatItem[] = [
  { title: "Total employees", apiEndpoint: "/api/github/usage", dataKey: "summary.active_users", accent: "#7b57e0" },
  { title: "Loyalty account", apiEndpoint: "/api/github/usage", dataKey: "summary.active_users", accent: "#50c099" },
  { title: "Average income", apiEndpoint: "/api/github/usage", dataKey: "summary.active_users", accent: "#5daaee", filter: "Month" },
  { title: "Campaign sent", apiEndpoint: "/api/github/usage", dataKey: "summary.active_users", accent: "#ffc565", filter: "Month" },
];

const defaultCalendarItems = [
  { title: "Summer Campaign is end!", time: "16:00", color: "#50c099" },
  { title: "2 plus 1 promotions is end!", time: "14:00", color: "#ffc565" },
  { title: "Winter Campaign is end!", time: "13:00", color: "#5daaee" },
  { title: "Summer Campaign is end!", time: "09:00", color: "#7b57e0" },
];

interface AnalyticsRendererProps {
  config: DashboardTool | null;
}

export function AnalyticsRenderer({ config }: AnalyticsRendererProps) {
  const renderToolComponent = (cfg: ChartConfig) => {
    if (cfg.component === 'KPIGrid') {
      return <KPIGrid apiEndpoint={cfg.apiEndpoint} definitions={cfg.kpiDefinitions} />;
    }
    if (cfg.component === 'SmartTable') {
      return <SmartTable apiEndpoint={cfg.apiEndpoint} title={cfg.title} columns={cfg.tableColumns || []} />;
    }
    return <SmartChart apiEndpoint={cfg.apiEndpoint} title={cfg.title} xAxisKey={cfg.xAxisKey} series={cfg.chartSeries} />;
  };

  const renderCenterContent = () => {
    if (!config) {
      return (
        <div className="h-full bg-white p-6 rounded-xl shadow-sm border border-gray-100 flex flex-col items-center justify-center text-center">
          <div className="w-16 h-16 bg-blue-50 rounded-full flex items-center justify-center mb-4">
            <span className="text-2xl">📈</span>
          </div>
          <h3 className="text-lg font-semibold text-gray-800">Analytics Ready</h3>
          <p className="text-gray-500 mt-2 max-w-sm">
            Open the Copilot chat on the right and ask for complex analysis.
          </p>
        </div>
      );
    }

    if (config.layout === 'dashboard') {
      return (
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100 animate-in fade-in zoom-in duration-500 h-full">
          <div className="mb-4 flex items-center justify-between">
            <h3 className="text-lg font-semibold text-gray-800">{config.slotMain.title}</h3>
            <span className="text-xs font-medium text-blue-600 bg-blue-50 px-2 py-1 rounded-full">Generated by Copilot</span>
          </div>
          {renderToolComponent(config.slotMain)}
        </div>
      );
    }

    if (config.layout === 'single') {
      return (
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100 animate-in fade-in zoom-in duration-500 h-full">
          <div className="mb-4 flex items-center justify-between">
            <h3 className="text-lg font-semibold text-gray-800">{config.config.title}</h3>
            <span className="text-xs font-medium text-blue-600 bg-blue-50 px-2 py-1 rounded-full">Generated by Copilot</span>
          </div>
          {renderToolComponent(config.config)}
        </div>
      );
    }

    if (config.layout === 'split') {
      return (
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100 animate-in fade-in zoom-in duration-500 h-full">
          <div className="mb-4 flex items-center justify-between">
            <h3 className="text-lg font-semibold text-gray-800">Comparison View</h3>
            <span className="text-xs font-medium text-blue-600 bg-blue-50 px-2 py-1 rounded-full">Generated by Copilot</span>
          </div>
          <SplitLayout 
            left={renderToolComponent(config.leftChart)}
            right={renderToolComponent(config.rightChart)}
          />
        </div>
      );
    }
    return null;
  };

  const currentStats = (config?.layout === 'dashboard' && config.headerStats) ? config.headerStats : defaultStats;
  const currentSideItems = (config?.layout === 'dashboard' && config.slotSide) ? config.slotSide.items : defaultCalendarItems;

  return (
    <div className="flex flex-col h-full">
      <section className="mb-6">
        <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">
          {currentStats.map((item, i) => (
            <SmartStatCard key={i} {...(item as StatItem)} />
          ))}
        </div>
      </section>

      <section className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_364px] flex-1">
        <div className="min-h-[400px]">
          {renderCenterContent()}
        </div>
        <Calendar items={currentSideItems} />
      </section>
    </div>
  );
}
